[project]
name = "week2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nbconvert>=7.16.6",
    "notebook>=7.4.5",
]
